### ISSUE TITLE
Error 500 when trying to open a report in web interface, database is locked

### ISSUE THREAD

**Issue by zach-sb** [gramps-project/gramps-web-api#478]
Hi, guessing this is a backend issue...

I am having this issue where sometimes (not all times) opening the reports section causes an Error 500. Sometimes I can open a specific report menu before getting the error. Other times I can successfully generate a report.

I am not sure what is the cause. One may be stopping and starting the container, but that is only my current guess. Regardless, the end result is loading any page that requires new data will not work, and eventually I am booted back to the login screen which then fails to ever log me back in. Nothing else works until I restart the containers, at which point everything seems fine until I try to open the reports again.

The only 'foolproof' way to get it back to functional is wipe the volumes, and re import my data into a fresh setup. This only works for a short while. I even attempted to use postgres, though I am not sure if it is the same error regardless... or if I didn't set it up properly.

# Error in UI
![image](https://github.com/gramps-project/gramps-webapi/assets/30288956/c208d47d-4ac7-4003-8a1b-79416aca8684)

# Logs
```
[2024-01-18 10:01:40 +0000] [14] [ERROR] Error handling request /api/reports/indiv_complete
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 178, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1471, in wsgi_app
    ctx.pop(error)
  File "/usr/local/lib/python3.11/dist-packages/flask/ctx.py", line 417, in pop
    app_ctx.pop(exc)
  File "/usr/local/lib/python3.11/dist-packages/flask/ctx.py", line 255, in pop
    self.app.do_teardown_appcontext(exc)
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1328, in do_teardown_appcontext
    self.ensure_sync(func)(exc)
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/app.py", line 180, in close_db
    db_write.close()
  File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 688, in close
    self._set_metadata('name_formats', self.name_formats)
  File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 341, in _set_metadata
    self._txn_commit()
  File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 217, in _txn_commit
    self.dbapi.commit()
  File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/sqlite.py", line 162, in commit
    self.__connection.commit()
sqlite3.OperationalError: database is locked
```

# Docker Compose file
```
services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: always
    ports:
      - "5026:5000"  # host:docker
    environment:
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GRAMPSWEB_IGNORE_DB_LOCK: true
      # the PostgreSQL addon assumes the tree name to be
      # equal to the database name and here the default
      # database name of the PostgreSQL image is used
      GRAMPSWEB_TREE: postgres
      # The credentials must agree with the ones used for
      # the PostgreSQL container
      GRAMPSWEB_POSTGRES_USER: postgres
      GRAMPSWEB_POSTGRES_PASSWORD: redacted

    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    labels:
      - homepage.group=Apps
      - homepage.name=Gramps
      - homepage.icon=gramps.png
      - homepage.description=Family Ancestry
      - homepage.href=redacted

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: always

  postgres_gramps:
    build: ./postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: redacted
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
  postgres_data:
```

**Comment by DavidMStraub** [comment]
It says `sqlite3.OperationalError: database is locked` but you write you are using PostgreSQL - so something is clearly wrong in the setup. Please check whether you have created the Gramps database with the right backend.

**Comment by zach-sb** [comment]
Okay that's a good to know that should be a different error for postgres. I'll look into that more.

That said I was only trying postgres to get around this sqlite issue in the first place, so there's still a problem there.

**Comment by DavidMStraub** [comment]
Yes. I don't understand why it's trying to write name formats to the metadata table - this is only supposed to happen when the database is not in readonly mode, but it should be, in this case.

**Comment by DavidMStraub** [comment]
I understand now why it's not in readonly mode, it's because of this change #401. However I still don't know why the lock error occurred - it means there were two processes simultaneously writing to the db.

And with Postgres, this should anyway never happen is Postgres is made for concurrent access. So are you seeing issues with Postgres as well?

**Comment by zach-sb** [comment]
I think I have Postgres actually working now, and have not seen that error appear again yet, though I have only had it going for about an hour now. I actually had to delete the 'postgres' family tree using the gramps cli before I could run the import for the docker version of the guide.

Anyway, postgres seems fine so far, but that was a bit more work than I had wanted in the first place when SQLite is built in and would have been fine for me if it didn't keep crashing.

**Comment by DavidMStraub** [comment]
It's not crashing, it's just not supporting concurrent write access. But when you are the only user, there shouldn't be any concurrent write access, so it would be worth checking your logs and/or browser console which multiple requests are interfering with each other there.

**Comment by DavidMStraub** [comment]
FYI I'm using SQLite and have never encountered this problem.

**Comment by zach-sb** [comment]
Okay, not crashing just becoming unusable until I restart it or maybe after long time left alone. 

I was playing with the Web Sync addon in gramps desktop, and I also have had multiple gramps tabs in my browser open at different points. Would either of those have caused the issue?

Postgres still working so far, so thats nice. I'll spin up another gramps container with just sqlite again when I have the chance and have a look.

**Comment by DavidMStraub** [comment]
If the sync addon or one of your tabs was doing something that needed write access, e.g. importing data, that would explain the issue, yes.

What I also don't understand is why it would render it unusable. I would expect SQLite to through the lock error, but once the competing requests are done, everything should be back to normal again.

**Comment by Shablone** [comment]
I'm faceing the same issue. Trying to open any report results in crashing the whole app. I use sqlite only


```
[2024-02-02 21:21:42 +0000] [14] [ERROR] Error handling request /api/reports/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1466, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 191, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 649, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/reports.py", line 51, in get
    reports = get_reports(
              ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/report.py", line 122, in get_reports
    report = get_report_profile(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/report.py", line 79, in get_report_profile
    report = ModifiedCommandLineReport(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/report.py", line 152, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gramps/cli/plug/__init__.py", line 264, in __init__
    _validate_options(self.option_class, database)
  File "/usr/lib/python3/dist-packages/gramps/cli/plug/__init__.py", line 161, in _validate_options
    person = dbase.get_person_from_gramps_id(pid)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1309, in get_person_from_gramps_id
    data = self._get_raw_person_from_id_data(gramps_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gramps/gen/db/generic.py", line 1702, in _get_raw_person_from_id_data
    return self._get_raw_from_id_data(PERSON_KEY, gramps_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/dbapi.py", line 877, in _get_raw_from_id_data
    self.dbapi.execute(sql, [gramps_id])
  File "/usr/lib/python3/dist-packages/gramps/plugins/db/dbapi/sqlite.py", line 133, in execute
    self.__cursor.execute(*args, **kwargs)
sqlite3.OperationalError: database is locked
```

my compose:
```
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: unless-stopped
    networks:
      - myserver_core_net_nginx
      - net_gramps
    environment:
      GRAMPSWEB_TREE: "Gramps Web"  # will create a new tree if not exists
      VIRTUAL_PORT: "5000"
      VIRTUAL_HOST: "grampsweb"  # e.g. gramps.mydomain.com
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
      GUNICORN_NUM_WORKERS: 2
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO
    networks:
      - net_gramps
    restart: unless-stopped

  grampsweb_redis:
    image: redis:alpine
    container_name: grampsweb_redis
    restart: unless-stopped
    networks:
      - net_gramps

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:

networks:
  myserver_core_net_nginx:
    external: true
  net_gramps:
```
