### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by Shablone** [gramps-project/gramps-web-api#487]
I added smtp configuration via environment variables to my docker-compose setup.
I use gmail app passwords for that. 

At first I tried this config:
```
EMAIL_HOST="smtp.gmail.com"
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_HOST_USER="xxxx"
EMAIL_HOST_PASSWORD="xxx"
```
Then I changed the port to 465 and restarted the compose.
Both setups throw an error in celery when a new user tries to register:

```
Task gramps_webapi.api.tasks.send_email_confirm_email[5d7d0d60-daa9-4961-9dd7-98d8bb59eca5] raised unexpected: ValueError('Error while trying to send e-mail.')
grampsweb_celery  | Traceback (most recent call last):
grampsweb_celery  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/util.py", line 399, in send_email
grampsweb_celery  |     smtp = smtplib.SMTP_SSL(host=host, port=port, timeout=10)
grampsweb_celery  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/lib/python3.11/smtplib.py", line 1050, in __init__
grampsweb_celery  |     SMTP.__init__(self, host, port, local_hostname, timeout,
grampsweb_celery  |   File "/usr/lib/python3.11/smtplib.py", line 255, in __init__
grampsweb_celery  |     (code, msg) = self.connect(host, port)
grampsweb_celery  |                   ^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/lib/python3.11/smtplib.py", line 341, in connect
grampsweb_celery  |     self.sock = self._get_socket(host, port, self.timeout)
grampsweb_celery  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/lib/python3.11/smtplib.py", line 1057, in _get_socket
grampsweb_celery  |     new_socket = self.context.wrap_socket(new_socket,
grampsweb_celery  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/lib/python3.11/ssl.py", line 517, in wrap_socket
grampsweb_celery  |     return self.sslsocket_class._create(
grampsweb_celery  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/lib/python3.11/ssl.py", line 1075, in _create
grampsweb_celery  |     self.do_handshake()
grampsweb_celery  |   File "/usr/lib/python3.11/ssl.py", line 1346, in do_handshake
grampsweb_celery  |     self._sslobj.do_handshake()
grampsweb_celery  | ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:992)
grampsweb_celery  |
grampsweb_celery  |
grampsweb_celery  | During handling of the above exception, another exception occurred:
grampsweb_celery  |
grampsweb_celery  |
grampsweb_celery  | Traceback (most recent call last):
grampsweb_celery  |   File "/usr/local/lib/python3.11/dist-packages/celery/app/trace.py", line 477, in trace_task
grampsweb_celery  |     R = retval = fun(*args, **kwargs)
grampsweb_celery  |                  ^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/util/celery.py", line 20, in __call__
grampsweb_celery  |     return self.run(*args, **kwargs)
grampsweb_celery  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
grampsweb_celery  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/tasks.py", line 77, in send_email_confirm_email
grampsweb_celery  |     send_email(subject=subject, body=body, to=[email])
grampsweb_celery  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/util.py", line 418, in send_email
grampsweb_celery  |     raise ValueError("Error while trying to send e-mail.")
grampsweb_celery  | ValueError: Error while trying to send e-mail.
```

**Comment by DavidMStraub** [comment]
Please don't open an issue for configuration problems.

**Comment by Shablone** [comment]
Well I think its a problem of the app and not the configuration
