### ISSUE TITLE
Gtk Error starting gramps-web-api on Ubuntu 22 and 23

### ISSUE THREAD

**Issue by Jimbosss** [gramps-project/gramps-web-api#509]
After succesfully cloning and installing the gramps-web-api on a brand new Ubuntu (22.04.4) on Virtualbox 7.0.12, I tried to add a new user using the given example on the website.

I got the following error:

check.py:51 PyGIWarning: Gtk was imported without specifying a version first...
.... AtributeError: type object 'IconSize' has no attribute 'MENU'

This has to do with the fact that Gtk4 is also present on the Ubuntu. But Gtk4 has abonded MENU.
to fix this problem, I had to add

gi.require_version("Gtk", "3.0")

After the "import gi" in ./home/gramps/.local/lib/Python310/site-packages/gramps/gen/utils/requirements.py

Maybe add the require line by default for future cases until Gtk4 is really used ?

P.S.

after running python3 -m gramps_webapi --config path/to/config user add owner owner --role 4

it said Error: gramps_webapi:Adding user owner ...

But running the API still works and could sync with the database. Maybe it said error because the user owner already existed ?

**Comment by DavidMStraub** [comment]
Hi,

interesting ... perhaps the command worked in the first place and the Gtk error was unrelated? Do you get the Gtk error also when you run Gramps? `gi` is only imported in code that is inside the gramps library, not Web API.

**Comment by Jimbosss** [comment]
> perhaps the command worked in the first place and the Gtk error was unrelated?
Yeah, I thought so too.

>  Do you get the Gtk error also when you run Gramps?
I could run Gramps just fine. Did not look at the logs.

> gi is only imported in code that is inside the gramps library, not Web API.

Did noticed it too, when I was looking for the location of the requirements.py in a separate Docker container.

Because I also tried on Windows 10 a seperate docker image with:  docker pull dmstraub/gramps-webapi:latest-devel
And got the same Gtk error. 
On the virtualbox, I could run the Development container fine.

I suspected that the connection with Gramps is in a other container, am I correct ?

**Comment by Jimbosss** [comment]
This is the full log of the docker container from dmstraub/gramps-webapi:latest-devel  :

2024-04-02 03:48:42 /usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
2024-04-02 03:48:42   from gi.repository import Gtk
2024-04-02 03:48:42 
2024-04-02 03:48:42 (__main__.py:12): Gtk-CRITICAL **: 01:48:42.561: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
2024-04-02 03:48:42 Traceback (most recent call last):
2024-04-02 03:48:42   File "<frozen runpy>", line 198, in _run_module_as_main
2024-04-02 03:48:42   File "<frozen runpy>", line 88, in _run_code
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 234, in <module>
2024-04-02 03:48:42     cli(
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
2024-04-02 03:48:42     return self.main(*args, **kwargs)
2024-04-02 03:48:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
2024-04-02 03:48:42     rv = self.invoke(ctx)
2024-04-02 03:48:42          ^^^^^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1685, in invoke
2024-04-02 03:48:42     super().invoke(ctx)
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
2024-04-02 03:48:42     return ctx.invoke(self.callback, **ctx.params)
2024-04-02 03:48:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
2024-04-02 03:48:42     return __callback(*args, **kwargs)
2024-04-02 03:48:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
2024-04-02 03:48:42     return f(get_current_context(), *args, **kwargs)
2024-04-02 03:48:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 53, in cli
2024-04-02 03:48:42     ctx.obj = {"app": create_app()}
2024-04-02 03:48:42                       ^^^^^^^^^^^^
2024-04-02 03:48:42   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/app.py", line 104, in create_app
2024-04-02 03:48:42     raise ValueError(f"{option} must be specified")
2024-04-02 03:48:42 ValueError: TREE must be specified
2024-04-02 03:49:37 /usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
2024-04-02 03:49:37   from gi.repository import Gtk
2024-04-02 03:49:37 
2024-04-02 03:49:37 (__main__.py:9): Gtk-CRITICAL **: 01:49:37.958: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
2024-04-02 03:49:38 Traceback (most recent call last):
2024-04-02 03:49:38   File "<frozen runpy>", line 198, in _run_module_as_main
2024-04-02 03:49:38   File "<frozen runpy>", line 88, in _run_code
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 234, in <module>
2024-04-02 03:49:38     cli(
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
2024-04-02 03:49:38     return self.main(*args, **kwargs)
2024-04-02 03:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
2024-04-02 03:49:38     rv = self.invoke(ctx)
2024-04-02 03:49:38          ^^^^^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1685, in invoke
2024-04-02 03:49:38     super().invoke(ctx)
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
2024-04-02 03:49:38     return ctx.invoke(self.callback, **ctx.params)
2024-04-02 03:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
2024-04-02 03:49:38     return __callback(*args, **kwargs)
2024-04-02 03:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
2024-04-02 03:49:38     return f(get_current_context(), *args, **kwargs)
2024-04-02 03:49:38            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 53, in cli
2024-04-02 03:49:38     ctx.obj = {"app": create_app()}
2024-04-02 03:49:38                       ^^^^^^^^^^^^
2024-04-02 03:49:38   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/app.py", line 104, in create_app
2024-04-02 03:49:38     raise ValueError(f"{option} must be specified")
2024-04-02 03:49:38 ValueError: TREE must be specified

**Comment by DavidMStraub** [comment]
Yeah because `TREE` must be specified ...

**Comment by Jimbosss** [comment]
I am a bit confused.
Shouldn't the TREE be configured in "GRAMPS_API_CONFIG=/app/config/config.cfg" from the container ?

And because of the error above, I can't run the container to change the files..

**Comment by DavidMStraub** [comment]
Is the issue fixed then?

**Comment by Jimbosss** [comment]
Yes. Stil don't like the Gtk warning, but that is a Gramps issue.
