### ISSUE TITLE
docker-setup with Multi-Tree support fails to start the web container

### ISSUE THREAD

**Issue by strombringer** [gramps-project/gramps-web-api#510]
I'm trying to setup a Multi-Tree installation with Docker and followed the instructions at https://www.grampsweb.org/Deployment/, but starting the grampsweb container fails with this error message:
```
/usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
(__main__.py:9): Gtk-CRITICAL **: 16:35:05.519: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 234, in <module>
    cli(
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 128, in search
    raise ValueError("`tree` is required when multi-tree support is enabled.")
ValueError: `tree` is required when multi-tree support is enabled.
```

I'm using [the docker-compose file linked in the documentation](https://raw.githubusercontent.com/gramps-project/gramps-web-docs/main/examples/docker-compose-base/docker-compose.yml), with minor changes:
Port, SECRET_KEY, TREE and MEDIA_PREFIX_TREE are changed
```
version: "3.7"

services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:latest
    restart: unless-stopped
    ports:
      - "13000:5000"  # host:docker
    environment:
      GRAMPSWEB_SECRET_KEY: "mysecret"
      GRAMPSWEB_TREE: "*"  # will create a new tree if not exists
      GRAMPSWEB_MEDIA_PREFIX_TREE: "True"
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
...
```

My understanding from the documentation is, 
- that this configuration should enable the 3 containers to start and
- then to be able to open `https://myhost:13000` to setup the server administrator account

Is my understanding wrong and I overlooked something? Where should I have setup the tree, that's mentioned in the error message?

Thanks in advance for the support!

**Comment by DavidMStraub** [comment]
Ok, I think that's a problem with our compose examples for multi-tree. Please try adding `entrypoint: []` to the `grampsweb` service.

**Comment by strombringer** [comment]
Thank you! With the `entrypoint` change I'm able to start the containers.

I'm still a bit lost on how to continue from here. Opening the service in the browser gives me the login form, but I don't have a user yet. The user registration doesn't work and from the documentation I know that it can't work in multi-tree mode and I should disable it. The "first-run wizard" that's mentioned in the documentation is not shown.

https://www.grampsweb.org/multi-tree/ says that users are tied to trees. If I want to create a tree, it is recommended to do that via the web api. But to do that, I need a JWT, which I get by authorizing as a user. That's a chicken and egg issue for me :D

**Comment by DavidMStraub** [comment]
It should show the first run wizard. Please check the container logs.

**Comment by DavidMStraub** [comment]
Did you specify `USER_DB_URI`? If not, please try that. If yes, please run

```
docker-compose run grampsweb python3 -m gramps_webapi --config /app/config/config.cfg user migrate
```

**Comment by strombringer** [comment]
I had not specified `USER_DB_URI`, as it was not needed for the single-tree installation.

I now added this to the compose.yml: `GRAMPSWEB_USER_DB_URI: "sqlite:////app/users/users.sqlite"`
This is the default setting anyway, right? At least it did not seem to have an effect.

I then ran 
`docker-compose run grampsweb python3 -m gramps_webapi --config /app/config/config.cfg user migrate`
and got this:
```
[+] Running 1/0
 ⠿ Container grampsweb_redis  Running                                                                                                                                  0.0s
/usr/local/lib/python3.11/dist-packages/gramps/plugins/tool/check.py:51: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk

(__main__.py:1): Gtk-CRITICAL **: 15:30:13.940: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  FAILED: No config file 'alembic.ini' found, or file has no '[alembic]' section
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 234, in <module>
    cli(
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/__main__.py", line 118, in migrate_db
    subprocess.run(cmd, env=env, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'alembic', 'upgrade', 'head']' returned non-zero exit status 255.
```
I tried the command with and without the `GRAMPSWEB_USER_DB_URI` setting. both returned the same result. I also cleared the volumes between each try, just to avoid any strange side effects.

**Comment by DavidMStraub** [comment]
Next try:

```bash
docker-compose run --entrypoint="" --rm -w /app/src grampsweb python3 -m gramps_webapi --config /app/config/config.cfg user migrate
```

Thanks for bearing with me :sweat_smile:

**Comment by strombringer** [comment]
I'm happy to work through this with your help 😄 

The last command worked and the first run wizard is shown in the browser. But when I enter my data and submit, I get a "Wrong username or password" error message:
![grafik](https://github.com/gramps-project/gramps-web-api/assets/3511229/ab2046ab-c000-451a-90c5-025e807a48cb)
SMTP data left empty, no tree to import.

I don't see any error messages in either of the three containers logs. When I try to submit again, I get the message "Users already exists" (I assume it should be "User").
Username is in the format "firstname-lastname" and password is 48 characters [a-zA-Z0-9], in case it makes a difference.

Going back to the root in the browser, I'm now presented with the login form again. But when trying to login, it says "Error: Wrong username or password"

**Comment by DavidMStraub** [comment]
Ha, that's weird because it means creating the user worked, but fetching a token didn't work, and the Javascript functions for both operations use the same variables for the username and password.

If you can start over and monitor the API calls in the browser dev console, that would be useful. Perhaps it's some weird special character issue, but I wouldn't see why...

**Comment by strombringer** [comment]
These are requests for loading the page, entering the user information and sending it (with placeholder data). Everything on a completely fresh installation.
![grafik](https://github.com/gramps-project/gramps-web-api/assets/3511229/d2986ba6-7b60-49af-b694-f3381414ed42)

I saved the requests as a HAR file. Github doesn't allow attaching it here, so I uploaded it to Dropbox: https://www.dropbox.com/scl/fi/mavy3l3xx2nioagnpyov7/192.168.178.52_Archive-24-04-23-20-47-23.har?rlkey=uscgu3imzgiwtkoyj7d3je2z5&dl=0

Maybe that's helpful for you 😄 

---
For completeness sake:

This is the part that's changed from the default compose.yml file:
```
    environment:
      GRAMPSWEB_SECRET_KEY: "mysecret"
      GRAMPSWEB_TREE: "*"
      GRAMPSWEB_MEDIA_PREFIX_TREE: "True"
      ...
    entrypoint: []
```
And I executed this command of yours:
```
docker-compose run --entrypoint="" --rm -w /app/src grampsweb python3 -m gramps_webapi --config /app/config/config.cfg user migrate
```

**Comment by strombringer** [comment]
I just realized I didn't mention this before: I tried the default compse.yml for a single-tree setup and there everything worked out of the box, with the same username and password that I tried for the multi-tree setup. So I don't think it's a special character issue.

**Comment by DavidMStraub** [comment]
Ok I think I know what's happening.

In the multi-tree setup, the first run wizard creates a site admin, not a tree owner. But the site admin does not have a tree. You would first have to create a tree, or to assign the admin to a specific tree. In a multi-tenant setup, the site admin might anyway just be a service account that is used to create new trees and manage trees, without being itself associated with a tree.

Of course, the UI for that doesn't make sense right now and needs to be changed - I'll open an issue in the frontend repo.

Your next step is to create a new tree via the API by posting to `/api/trees/`. It will return a tree ID. You can then go to `https://yourgrampsweb/firstrun/<treeid>` to get the first run wizard *for the tree owner*.

**Comment by DavidMStraub** [comment]
(Thanks by the way for the detailed logs, very helpful!)

**Comment by strombringer** [comment]
For posting to `/api/trees`, I need a JWT. Otherwise I get a 401 error (as it should be). But when I try POSTing to `/api/token` with the username and password from the first run wizard, I get a 403 error.

Do I need to copy the token from the web session, for creating the first tree? I expected that the call to `api/token` should work in any case.

**Comment by DavidMStraub** [comment]
Right :man_facepalming: I take that back:

> Ok I think I know what's happening.

Your logs showed you got a 403 permission denied when trying to fetch a token with username/password, which *should* work regardless of tree. I will try to reproduce this later, there must be a bug somewhere.

**Comment by Corepex** [comment]
@strombringer did you manage to create a tree via the api endpoint?

**Comment by strombringer** [comment]
@Corepex no, I didn't. After the last test in April, I switched to single-tree mode and the setup wizard worked for that. I'll try again when a bugfix is available, though it's not high priority for me.

**Comment by DavidMStraub** [comment]
FYI, I am running a multi tree setup and creating new trees via the API all the time, so there could be a bug, but it's not obvious to me what it is as I'm not affected by it.

**Comment by letsjustfixit** [comment]
@DavidMStraub 
I've just ran into this issue myself: I've used the official docker-compose.yml sample like this:

```yml
services:
  grampsweb: &grampsweb
    image: ghcr.io/gramps-project/grampsweb:v24.10.0
    restart: always
    ports:
      - "80:5000"  # host:docker
    environment:
      GRAMPSWEB_TREE: "*"  # will create a new tree if not exists
      GUNICORN_NUM_WORKERS: 2
      GRAMPSWEB_SECRET_KEY: "__top_secret__"
      GRAMPSWEB_REGISTRATION_DISABLED: "True"
      GRAMPSWEB_MEDIA_PREFIX_TREE: "True"
      GRAMPSWEB_CELERY_CONFIG__broker_url: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_CELERY_CONFIG__result_backend: "redis://grampsweb_redis:6379/0"
      GRAMPSWEB_RATELIMIT_STORAGE_URI: redis://grampsweb_redis:6379/1
    depends_on:
      - grampsweb_redis
    volumes:
      - gramps_users:/app/users  # persist user database
      - gramps_index:/app/indexdir  # persist search index
      - gramps_thumb_cache:/app/thumbnail_cache  # persist thumbnails
      - gramps_cache:/app/cache  # persist export and report caches
      - gramps_secret:/app/secret  # persist flask secret
      - gramps_db:/root/.gramps/grampsdb  # persist Gramps database
      - gramps_media:/app/media  # persist media files
      - gramps_tmp:/tmp

  grampsweb_celery:
    <<: *grampsweb  # YAML merge key copying the entire grampsweb service config
    ports: []
    container_name: grampsweb_celery
    depends_on:
      - grampsweb_redis
    command: celery -A gramps_webapi.celery worker --loglevel=INFO --concurrency=2

  grampsweb_redis:
    image: docker.io/library/redis:7.2.4-alpine
    container_name: grampsweb_redis
    restart: always

volumes:
  gramps_users:
  gramps_index:
  gramps_thumb_cache:
  gramps_cache:
  gramps_secret:
  gramps_db:
  gramps_media:
  gramps_tmp:
```



- [x] ran `docker compose up -d` . 
- [x] I've got to the first time setup screen. I've filled in the required inputs: username, email, full_name, password:
- [x] It was POST ed to /api/users/{username}/create_owner return with 201, so succesfully created
```json
{"password":"pwd","email":"a@a.a","full_name":"fn"}
```
- [ ]  POST the username + password to the /api/token/ endpoint returned with  403
```json
{"error": {"code": 403, "message": "Forbidden"}}
```
---
Could you share your steps setting up a multi tree instance?
I've also tried without the gui like this ( docker exec -ti [container] bash ):
```bash
python3 -m gramps_webapi --config /app/config/config.cfg user add --role 5 username password
```
it had the same outcome

**Comment by DavidMStraub** [comment]
Ok, the error is issued by this function: https://github.com/gramps-project/gramps-web-api/blob/master/gramps_webapi/api/util.py#L590-L592.

So the prolem is that it's not possible to fetch a token with an account that doesn't have a tree ID, but the admin account created in the multi-tree setup doesn't have one. I have to think about what the best solution is. Maybe to create a new tree for the admin.

The solution for you right now is to use the command line as you did, but add the `--tree` parameter. The value should be a tree ID, which is the name of your tree dicrectory, e.g. `~/.gramps/grampsdb/<my-tree-id>`.

**Comment by letsjustfixit** [comment]
Thanks for the tip ⚡, this got the ball rolling (verbose notes for future reference) :

1️⃣First I've created an empty directory: 
`mkdir /root/.gramps/grampsdb/1`
Deleted my existing user: 
```
python3 -m gramps_webapi --config /app/config/config.cfg user delete username
```

2️⃣And created a new user with that same treeid:
```
python3 -m gramps_webapi --config /app/config/config.cfg user add --role 5 --tree 1 username password
```
That resulted in an internal error 500 firing for the first `/api/metadata/` request because it had a problem `processing dbmgr = get_db_manager(tree)`
Eventually I've started a single tree instance to look at what kind of folder is created by default and if any what kind of content is expected by running the following command:
```
docker run --rm -p "5055:5000" -e GRAMPSWEB_TREE=new --name=grampstemp ghcr.io/gramps-project/grampsweb:latest
```
Looked into the container: 
```
docker exec -ti grampstemp bash
ls -R /root/.gramps/grampsdb/
```
The result was only two files:
- /root/.gramps/grampsdb/f9811c2d-37b7-43cb-8b07-7f1fe6741093/database.txt
Content: `sqlite`
- /root/.gramps/grampsdb/f9811c2d-37b7-43cb-8b07-7f1fe6741093/name.txt
Content: `new`


3️⃣I've copied those files to my container using `docker cp` hit refersh: and I got to a proper admin UI.

---
🏆🍾 Thank you!

**Comment by DavidMStraub** [comment]
You can use `python3 -m gramps_webapi --config /app/config/config.cfg tree list` to find out the tree ID. Use python3 -m gramps_webapi --config /app/config/config.cfg --help` to find all available commands.

**Comment by vincentkoevoets** [comment]
I've been struggling some time with this too, and the information on this page pointed me in the right direction. It seems like for now, we have to accept that we need an administrative account with a tree assigned to it, in order to be able to create a new tree via the api /trees endpoint. Which is a b*tch, because:
1: We cannot create an admin account via the normal firstrun screen because this will fail on not finding a tree assigned to the admin account. 
2: We cannot connect to the endpoint to create a tree to assign to the admin account, because we are not allowed to login with an admin account without a tree assigned to it.. 
So this way we are running in circles. I solved the riddle by first creating a single tree instance. After that I stopped the containers, and deleted everything in the persistant (mounted) volumes, except the db folder with the tree id as the name. 
I moved that folder to a temp folder somewhere else. After that, I spun up the multi tree instance again, and while it was running I moved the db folder back in place. I was able to create the admin user in the gramps_webapi with the `--tree` option pointing to the same db folder. Great! Now we have an admin account, with a tree assigned to it. 
After that, I was able to create a new tree via the /trees endpoint, and create a new owner account on the `firstrun` page. Now, we have 2 cleanly seperated trees, of which one is not in use because I use this only for the admin account.

After all this, I started to wonder if maybe a 'real' admin console would be an idea? On without a tree assigned to it, and where you can create/edit/delete users/owners and trees. But maybe this is more a feature request. 
For now, everything is working at least. 
A big thanks to the dev, this is truly amazing software!

**Comment by dstraub-pf** [comment]
> After all this, I started to wonder if maybe a 'real' admin console would be an idea?

This is a feature request on the frontend repo and it already exists (the request, not the feature): https://github.com/gramps-project/gramps-web/issues/427

Of course, that would be super nice to have...

**Comment by DavidMStraub** [comment]
> After all this, I started to wonder if maybe a 'real' admin console would be an idea?

This is a feature request on the frontend repo and it already exists (the request, not the feature): https://github.com/gramps-project/gramps-web/issues/427

Of course, that would be super nice to have...

**Comment by DavidMStraub** [comment]
I'll close that issue here because this is a frontend issue and is tracked in https://github.com/gramps-project/gramps-web/issues/435.
