### ISSUE TITLE
Add revert option to undo history endpoints

### ISSUE THREAD

**Issue by DavidMStraub** [gramps-project/gramps-web-api#511]
After merging #506, it is relatively simple to add a "revert" endpoint for individual transactions.

The only non-trivial point is how to deal with conflicts, i.e. transactions where the affected objects have changed in the meantime. Fail, overwrite, merge?

**Comment by Luensche** [comment]
It would be nice if you could revert up to a revision. Maybe it's a little easier, because you don't have to look for merge or overwrite.

**Comment by Luensche** [comment]
> The only non-trivial point is how to deal with conflicts, i.e. transactions where the affected objects have changed in the meantime. Fail, overwrite, merge?

Personally, I would like to get a popup which shows the conflicts and to choose, which values I want to have. Maybe a bit like the merge dialogue in GRAMPS directly.

**Comment by DavidMStraub** [comment]
Brilliant, glad you resolved your issue and thanks for sharing the steps!

> Is there any advantage to doing this on the api end instead of purely client-side?

Yes I'd say it's much more user friendly to a Web API consumer (which doesn't have to be the Gramps Web frontend) to have a simple endpoint that automatically does what you did manually. It also means only a simple HTTP post without *any* data sent is sufficient, while your approach requires downloading, manipulating, and re-uploading a potentially large JSON file.

So the fact that what you did *can* be done is actually a positive aspect of the Web API being flexible and usable standalone.

Another advantage of implementing the logic in the backend is that the frontend becomes less dependent on backend implementation details (just thinking about the Gramps 5&to;6 schema changes for instance).

That being said, implementing it shouldn't be hard, "someone" just needs to sit down and to it 🙂 

> Side question: Should I add these steps and possibly the script I used to the docs somewhere, or would it be enough to just link people back to this post until this feature is added?

I think this thread is perfectly fine as a place to document this workaround for expert users.

> The cool thing here is that all of this can be done from the client side, where we could add user configurable options for how to deal with any conflicts in the form of a setting or a separate button for overwrite or merge.

In the backend implementation, initially I would envisage three options:

1. Just ask whether it can be undone without conflict (true/false)
2. Undo without force
3. Undo with force

The frontend logic would then be:

1. Ask if it can be undone without conflict.
2. If yes, offer undo button
3. If no, offer undo button warning that changes will be overwritten

An even better implementation would be one where the diff of the changes is returned as a JSON, so the frontend can show the conflicts to help the user decide.

**Comment by lekorrigan** [comment]
Hello, I have been a muppet and deleted most of my tree when using web sync the wrong way (and, of course, hadn't done a backup just before, being a double muppet). So I am trying this.
I have tried @Aliervo's method [above ](https://github.com/gramps-project/gramps-web-api/issues/511#issuecomment-3251262874), but unfortunately I still get a 500 error, with the following traceback: 

> [ERROR] Error handling request /api/transactions/?undo=true
> Traceback (most recent call last):
> File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 134, in handle
> self.handle_request(listener, req, client, addr)
> File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 177, in handle_request
> respiter = self.wsgi(environ, resp.start_response)
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1536, in __call__
> return self.wsgi_app(environ, start_response)
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1514, in wsgi_app
> response = self.handle_exception(e)
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1511, in wsgi_app
> response = self.full_dispatch_request()
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 919, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 917, in full_dispatch_request
> rv = self.dispatch_request()
> File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 902, in dispatch_request return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 110, in view
> return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 191, in dispatch_request
> return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
> File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 650, in wrapper
> return func(*args, **kwargs)
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/transactions.py", line 59, in post
> payload = reverse_transaction(payload)
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 1284, in reverse_transaction
> "type": type_reversed[item["type"]],
> 
> TypeError: string indices must be integers, not 'str'

I'm not sure how to proceed; I have changed all "type": from numbers to strings already. 
If you prefer a new thread for this, apologies, I can change it.
Thanks!

**Comment by lekorrigan** [comment]
Thank you: I had indeed left the `{  "changes":` at the beginning.
So now I can get new kinds of errors! Specifically, I now get the following:

> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/util/celery.py", line 18, in __call__
>    return self.run(*args, **kwargs)
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/tasks.py", line 506, in process_transactions
>   new_obj = gramps_object_from_dict(new_data)
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/util.py", line 783, in gramps_object_from_dict
>   return data_to_object(complete_gramps_object_dict(data))
> File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/util.py", line 759, in complete_gramps_object_dict
>  for key, value in data.items():
> AttributeError: 'list' object has no attribute 'items'

Unsure why. Now my file has the structure:
```
[
    {
      "new": {},
      "_class": "7",
      "handle": "68bbd929-4926-4089-8a3f-41cbf44cb3d0",
      "old": [
        "68bbd929-4926-4089-8a3f-41cbf44cb3d0",
        "Person",
        "ffbd900eb7f3bc58de8b22cf5e6",
        "Family"
      ],
      "type": "delete"
    },
(many more, some much longer)
]
```

**Comment by Aliervo** [comment]
You're almost there now!

You just need to delete any objects/dictionaries of class 7. Those changes are the links between other gramps objects (in your example it's the link between a Person and Family). These are also included in the individual People, Families, Citations, etc,  so the class 7 changes will be regenerated for you (in my chunk, you can see a "family_list", a "parent_family_list", and a few more).

Scrolling back up, I mistyped that in my previously provided steps, calling it "type" instead of "_class".  I'll go edit it just in case someone else has this problem before we manage to implement this!
