### ISSUE TITLE
Server fails (code 500) when private families are in DB

### ISSUE THREAD

**Issue by ant20879g** [gramps-project/gramps-web-api#523]
> Gramps 5.2.2
> Gramps Web API 2.3.1
> Gramps Web Frontend 24.6.0
> Gramps QL 0.3.0
> locale: en
> multi-tree: false
> task queue: true

`GET /api/families/?locale=en&profile=self&keys=gramps_id,profile,change&page=2&pagesize=20)`
I marked few families as private, there're more than 20 non-families. Based on default filter all private families are at the end of the list or on the second page. GET works for first page and crashes for second one.

**Comment by DavidMStraub** [comment]
It can't be because of families being private, there must be another reason.

Please check the server logs and report them here. 500 always means a Python exception is thrown.

**Comment by DavidMStraub** [comment]
Please also try whether the problem persists after running check & repair on your database.

**Comment by ant20879g** [comment]
> grampsweb-1  | [2024-07-15 01:08:13 +0000] [15] [ERROR] Error handling request /api/families/?locale=en&profile=self&keys=gramps_id,profile,change&page=2&pagesize=20
> grampsweb-1  | Traceback (most recent call last):
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 135, in handle
> grampsweb-1  |     self.handle_request(listener, req, client, addr)
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gunicorn/workers/sync.py", line 178, in handle_request
> grampsweb-1  |     respiter = self.wsgi(environ, resp.start_response)
> grampsweb-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1498, in __call__
> grampsweb-1  |     return self.wsgi_app(environ, start_response)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1476, in wsgi_app
> grampsweb-1  |     response = self.handle_exception(e)
> grampsweb-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 1473, in wsgi_app
> grampsweb-1  |     response = self.full_dispatch_request()
> grampsweb-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 882, in full_dispatch_request
> grampsweb-1  |     rv = self.handle_user_exception(e)
> grampsweb-1  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 880, in full_dispatch_request
> grampsweb-1  |     rv = self.dispatch_request()
> grampsweb-1  |          ^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/app.py", line 865, in dispatch_request
> grampsweb-1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/auth.py", line 44, in wrapper
> grampsweb-1  |     return func(*args, **kwargs)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 110, in view
> grampsweb-1  |     return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/flask/views.py", line 191, in dispatch_request
> grampsweb-1  |     return current_app.ensure_sync(meth)(**kwargs)  # type: ignore[no-any-return]
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 649, in wrapper
> grampsweb-1  |     return func(*args, **kwargs)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 446, in get
> grampsweb-1  |     [self.full_object(obj, args, locale=locale) for obj in objects],
> grampsweb-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 446, in <listcomp>
> grampsweb-1  |     [self.full_object(obj, args, locale=locale) for obj in objects],
> grampsweb-1  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 93, in full_object
> grampsweb-1  |     obj = self.object_extend(obj, args, locale=locale)
> grampsweb-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/families.py", line 55, in object_extend
> grampsweb-1  |     obj.profile = get_family_profile_for_object(
> grampsweb-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 505, in get_family_profile_for_object
> grampsweb-1  |     "father": get_person_profile_for_handle(
> grampsweb-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 473, in get_person_profile_for_handle
> grampsweb-1  |     return get_person_profile_for_object(db_handle, obj, args, locale=locale)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 399, in get_person_profile_for_object
> grampsweb-1  |     birth, birth_event = get_birth_profile(
> grampsweb-1  |                          ^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 266, in get_birth_profile
> grampsweb-1  |     event = get_birth_or_fallback(db_handle, person)
> grampsweb-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps/gen/utils/db.py", line 59, in get_birth_or_fallback
> grampsweb-1  |     birth_ref = person.get_birth_ref()
> grampsweb-1  |                 ^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  | AttributeError: 'NoneType' object has no attribute 'get_birth_ref'

This happens when public family has private parents. **gramps** lib's` sanitize_family()` does not set parent handle when it's private, so family with null in one or two handle is legitimate case. For this particular case [this](https://github.com/gramps-project/gramps-web-api/blob/c6dbfd4cc78309bb23ea1a0dbb0ed397f84f900e/gramps_webapi/api/resources/util.py#L473) line better to be in try/finally block.

**Comment by ant20879g** [comment]
When I make family private (for private parents) I'm getting slightly different error:
> ...some lines are skipped for clarity...
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/webargs/core.py", line 649, in wrapper
> grampsweb-1  |     return func(*args, **kwargs)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 446, in get
> grampsweb-1  |     [self.full_object(obj, args, locale=locale) for obj in objects],
> grampsweb-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 446, in <listcomp>
> grampsweb-1  |     [self.full_object(obj, args, locale=locale) for obj in objects],
> grampsweb-1  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/base.py", line 93, in full_object
> grampsweb-1  |     obj = self.object_extend(obj, args, locale=locale)
> grampsweb-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/families.py", line 55, in object_extend
> grampsweb-1  |     obj.profile = get_family_profile_for_object(
> grampsweb-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 514, in get_family_profile_for_object
> grampsweb-1  |     "children": [
> grampsweb-1  |                 ^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 515, in <listcomp>
> grampsweb-1  |     get_person_profile_for_handle(
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 473, in get_person_profile_for_handle
> grampsweb-1  |     return get_person_profile_for_object(db_handle, obj, args, locale=locale)
> grampsweb-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 399, in get_person_profile_for_object
> grampsweb-1  |     birth, birth_event = get_birth_profile(
> grampsweb-1  |                          ^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/resources/util.py", line 266, in get_birth_profile
> grampsweb-1  |     event = get_birth_or_fallback(db_handle, person)
> grampsweb-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  |   File "/usr/local/lib/python3.11/dist-packages/gramps/gen/utils/db.py", line 59, in get_birth_or_fallback
> grampsweb-1  |     birth_ref = person.get_birth_ref()
> grampsweb-1  |                 ^^^^^^^^^^^^^^^^^^^^
> grampsweb-1  | AttributeError: 'NoneType' object has no attribute 'get_birth_ref'
 
I do not see families with private children in my DB, however, at the end it still crashes when `get_person_profile_for_object()` is called with null in the second parameter.

**Comment by ant20879g** [comment]
Forgot to mention before, DB check did not find any errors.

**Comment by DavidMStraub** [comment]
Thanks! I see the problem &ndash; Gramps' `PrivateProxyDb` returns `None` if a person is private rather than `HandleError` :fearful:  Why, actually?

**Comment by Nick-Hall** [comment]
The return value of `None` indicates that the handle exists, but has been filtered out by the proxy.  The `HandleError` exception is a real error - the handle is referenced by an object, but doesn't actually exist.

In the past we used `None` for both cases, but this made tracking down errors very difficult and we had a large number of reports of associated `NoneType` errors.

**Comment by DavidMStraub** [comment]
> and we had a large number of reports of associated NoneType errors.

Such a great argument in favour of type hints :wink:

**Comment by Nick-Hall** [comment]
The main problem was that we didn't raise an exception for the errors.  They just slipped through looking like proxy filtering.
