### ISSUE TITLE
Manual search index update failure

### ISSUE THREAD

**Issue by MrTrustor** [gramps-project/gramps-web-api#564]
After updating to 2.5.0 (frontend 24.10.0), Gramps is prompting me to manually rebuild the search index. However, when I try to do that through the UI, it fails. Given the logs, this may be a side effect of the fix for #552. I'm using PostgreSQL as the search index database.

I will try to investigate this and propose a fix. I'd appreciate any pointers you may have.

## Screenshot

![Screenshot 2024-11-01 134902](https://github.com/user-attachments/assets/92d812c0-5083-49d1-9aa4-4f53a9cc8958)

## Logs

```
$ kubectl -n gramps logs gramps-0 -c celery --tail=29
[2024-11-01 20:48:34,012: INFO/MainProcess] Task gramps_webapi.api.tasks.search_reindex_full[13481937-c79e-4a21-aa7d-30aaed4e3435] received
[2024-11-01 20:48:34,018: ERROR/ForkPoolWorker-7] Task gramps_webapi.api.tasks.search_reindex_full[13481937-c79e-4a21-aa7d-30aaed4e3435] raised unexpected: UnpickleableExceptionWrapper('gramps.gen.db.exceptions', 'DbConnectionError', (), 'DbConnectionError()')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/util/celery.py", line 20, in __call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/tasks.py", line 144, in search_reindex_full
    return _search_reindex_full(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/tasks.py", line 114, in _search_reindex_full
    db = get_db_outside_request(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/api/util.py", line 390, in get_db_outside_request
    dbstate = dbmgr.get_db(user_id=user_id, readonly=readonly)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/dbmanager.py", line 179, in get_db
    smgr.open_activate(
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/dbloader.py", line 188, in open_activate
    self.read_file(filename, mode, username, password)
  File "/usr/local/lib/python3.11/dist-packages/gramps_webapi/dbloader.py", line 161, in read_file
    self.dbstate.db.load(
  File "/usr/local/lib/python3.11/dist-packages/gramps/gen/db/generic.py", line 647, in load
    self._initialize(directory, username, password)
  File "/root/.gramps/gramps52/plugins/PostgreSQL/postgresql.py", line 107, in _initialize
    raise DbConnectionError(str(msg), config_file)
celery.utils.serialization.UnpickleableExceptionWrapper: DbConnectionError()
```

## Configuration info
Gramps 5.2.3
Gramps Web API 2.5.0
Gramps Web Frontend 24.10.0
Gramps QL 0.3.0
Sifts 1.0.0
locale: en
multi-tree: false
task queue: true
OCR: true
chat: false

**Comment by DavidMStraub** [comment]
Thanks for investigating, I don't have an immediate idea...

**Comment by MrTrustor** [comment]
That one is on me, this was a configuration mistake on Celery where I wasn't using the correct environment variables.
