### ISSUE TITLE
Refactor api to not load all libraries

### ISSUE THREAD

**Issue by dsblank** [gramps-project/gramps-web-api#585]
Some of the endpoints (like the Chat support) require many GB of libraries, and an openAI key. It would be nice to be able to configure (frontend and server) to be able to enable/disable endpoints.

I've started a draft PR for discussion for the server side: #582

**Comment by DavidMStraub** [comment]
The AI example is one where I think it's handled in the way it should: the libraries are optional dependencies (`ai = ["sentence-transformers", "openai"]` in `pyproject.toml` and the libraries are only loaded in functions that are only called if the feature is enabled. For instance, you'll notice that if `sentence-transformers` is not installed, no `ImportError` will be raised. Even if it's installed and `VECTOR_EMBEDDING_MODEL` is not set, the library is loaded.

Likewise for OpenCV which is used for face detection: it's only loaded in a function when the explicit endpoint is called, and a 501 is raised if OpenCV is not installed. (Admittedly, in this it's a bit inconsistent as OpenCV is not even listed in the TOML due to the subtleties of installing it.)

The only library that is always loaded even though it's just needed for a single endpoint is `pytesseract` used for OCR. There, I think it would make sense to also move the import into a function and make the depdency optional.

Is there anything else you were thinking of? I think making dependencies optional and having the endpoints raise 501 or 405 in their absence is the right approach.

**Comment by dsblank** [comment]
I'm confused. If I remove `openai` and `sentence-transformers` then I get:

```
Traceback (most recent call last):
  File "/home/dsblank/miniconda3/envs/py310/bin/gwd", line 33, in <module>
    sys.exit(load_entry_point('gramps-web-desktop', 'console_scripts', 'gwd')())
  File "/home/dsblank/gramps/gramps-web-desktop/gramps_web_desktop/main.py", line 126, in main
    runpy.run_module("gramps_webapi", run_name="__main__")
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/runpy.py", line 227, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/__main__.py", line 37, in <module>
    from .api.search import get_search_indexer
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/__init__.py", line 27, in <module>
    from ..const import API_PREFIX
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/const.py", line 26, in <module>
    from pkg_resources import resource_filename
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'openai; extra == "ai"' distribution was not found and is required by gramps-webapi
```

Did I install something incorrectly, or does it not work the way you describe?

**Comment by DavidMStraub** [comment]
Which command are you running when you get this? Can you provide a minimal example? Is this using v2.6.0?

**Comment by dsblank** [comment]
Minimal example:

```
python -m gramps_webapi --config /tmp/gramps-web-azj4s3dy.cfg
```

Yes, 2.6.0.

**Comment by dsblank** [comment]
Although the minimal example is a different error:

```
Traceback (most recent call last):
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/dsblank/miniconda3/envs/py310/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/__main__.py", line 37, in <module>
    from .api.search import get_search_indexer
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/__init__.py", line 594, in <module>
    register_endpoints(ENDPOINT_MAP.keys())
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/__init__.py", line 589, in register_endpoints
    ENDPOINT_MAP[group_name]()
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/__init__.py", line 393, in register_chat
    from .resources.chat import ChatResource
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/resources/chat.py", line 25, in <module>
    from ..llm import answer_prompt_retrieve
  File "/home/dsblank/gramps/gramps-web-api/gramps_webapi/api/llm/__init__.py", line 6, in <module>
    from openai import OpenAI, RateLimitError, APIError
ImportError: cannot import name 'OpenAI' from 'openai' (unknown location)
```

**Comment by DavidMStraub** [comment]
Oh, right, we have to move the `openai` import into a function.

**Comment by DavidMStraub** [comment]
I checked that when `openai` is moved to functions, nothing else is erroring in a freh venv with only setuptools.

**Comment by DavidMStraub** [comment]
The issue with `openai` being imported at top level should now be solved, with #594 merged.

**Comment by dsblank** [comment]
Nice! Thanks!

**Comment by DavidMStraub** [comment]
Can we close this issue?
